# This file is part of WebKeyPass.
#
# Copyright © 2013 Université Catholique de Louvain
#
# WebKeyPass is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# WebKeyPass is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WebKeyPass.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Sébastien Wilmet

# Root

ucl_wkp_root_view:
    pattern: /
    defaults: { _controller: UCLWebKeyPassBundle:RootNode:viewRoot }

ucl_wkp_root_add_category:
    pattern: /add_category
    defaults: { _controller: UCLWebKeyPassBundle:RootNode:addCategory }

# Category

ucl_wkp_category_view:
    pattern: /category/{node_id}
    defaults: { _controller: UCLWebKeyPassBundle:CategoryNode:view }

ucl_wkp_category_edit:
    pattern: /category/{node_id}/edit
    defaults: { _controller: UCLWebKeyPassBundle:CategoryNode:edit }

ucl_wkp_category_add_server:
    pattern: /category/{node_id}/add_server
    defaults: { _controller: UCLWebKeyPassBundle:CategoryNode:addServer }

ucl_wkp_category_add_subcategory:
    pattern: /category/{node_id}/add_subcategory
    defaults: { _controller: UCLWebKeyPassBundle:CategoryNode:addSubCategory }

ucl_wkp_category_add_misc:
    pattern: /category/{node_id}/add_misc
    defaults: { _controller: UCLWebKeyPassBundle:CategoryNode:addMisc }

ucl_wkp_category_move:
    pattern: /category/{node_id}/move
    defaults: { _controller: UCLWebKeyPassBundle:CategoryNode:move }

ucl_wkp_category_remove:
    pattern: /category/{node_id}/remove
    defaults: { _controller: UCLWebKeyPassBundle:CategoryNode:remove }

# Server

ucl_wkp_server_view:
    pattern: /server/{node_id}
    defaults: { _controller: UCLWebKeyPassBundle:ServerNode:view }

ucl_wkp_server_edit:
    pattern: /server/{node_id}/edit
    defaults: { _controller: UCLWebKeyPassBundle:ServerNode:edit }

ucl_wkp_server_add_login:
    pattern: /server/{node_id}/add_login
    defaults: { _controller: UCLWebKeyPassBundle:ServerNode:addLogin }

ucl_wkp_server_edit_login:
    pattern: /server/{node_id}/edit_login_{auth_id}
    defaults: { _controller: UCLWebKeyPassBundle:ServerNode:editLogin }

ucl_wkp_server_remove_login:
    pattern: /server/{node_id}/remove_login_{auth_id}
    defaults: { _controller: UCLWebKeyPassBundle:ServerNode:removeLogin }

ucl_wkp_server_add_vm:
    pattern: /server/{node_id}/add_vm
    defaults: { _controller: UCLWebKeyPassBundle:ServerNode:addVM }

ucl_wkp_server_add_misc:
    pattern: /server/{node_id}/add_misc
    defaults: { _controller: UCLWebKeyPassBundle:ServerNode:addMisc }

ucl_wkp_server_move:
    pattern: /server/{node_id}/move
    defaults: { _controller: UCLWebKeyPassBundle:ServerNode:move }

ucl_wkp_server_remove:
    pattern: /server/{node_id}/remove
    defaults: { _controller: UCLWebKeyPassBundle:ServerNode:remove }

# Virtual Machine

ucl_wkp_vm_view:
    pattern: /vm/{node_id}
    defaults: { _controller: UCLWebKeyPassBundle:VMNode:view }

ucl_wkp_vm_edit:
    pattern: /vm/{node_id}/edit
    defaults: { _controller: UCLWebKeyPassBundle:VMNode:edit }

ucl_wkp_vm_add_login:
    pattern: /vm/{node_id}/add_login
    defaults: { _controller: UCLWebKeyPassBundle:VMNode:addLogin }

ucl_wkp_vm_edit_login:
    pattern: /vm/{node_id}/edit_login_{auth_id}
    defaults: { _controller: UCLWebKeyPassBundle:VMNode:editLogin }

ucl_wkp_vm_remove_login:
    pattern: /vm/{node_id}/remove_login_{auth_id}
    defaults: { _controller: UCLWebKeyPassBundle:VMNode:removeLogin }

ucl_wkp_vm_add_misc:
    pattern: /vm/{node_id}/add_misc
    defaults: { _controller: UCLWebKeyPassBundle:VMNode:addMisc }

ucl_wkp_vm_move:
    pattern: /vm/{node_id}/move
    defaults: { _controller: UCLWebKeyPassBundle:VMNode:move }

ucl_wkp_vm_remove:
    pattern: /vm/{node_id}/remove
    defaults: { _controller: UCLWebKeyPassBundle:VMNode:remove }

# Misc nodes

ucl_wkp_misc_view:
    pattern: /misc/{node_id}
    defaults: { _controller: UCLWebKeyPassBundle:MiscNode:view }

ucl_wkp_misc_edit:
    pattern: /misc/{node_id}/edit
    defaults: { _controller: UCLWebKeyPassBundle:MiscNode:edit }

ucl_wkp_misc_add_login:
    pattern: /misc/{node_id}/add_login
    defaults: { _controller: UCLWebKeyPassBundle:MiscNode:addLogin }

ucl_wkp_misc_edit_login:
    pattern: /misc/{node_id}/edit_login_{auth_id}
    defaults: { _controller: UCLWebKeyPassBundle:MiscNode:editLogin }

ucl_wkp_misc_remove_login:
    pattern: /misc/{node_id}/remove_login_{auth_id}
    defaults: { _controller: UCLWebKeyPassBundle:MiscNode:removeLogin }

ucl_wkp_misc_add_misc:
    pattern: /misc/{node_id}/add_misc
    defaults: { _controller: UCLWebKeyPassBundle:MiscNode:addMisc }

ucl_wkp_misc_move:
    pattern: /misc/{node_id}/move
    defaults: { _controller: UCLWebKeyPassBundle:MiscNode:move }

ucl_wkp_misc_remove:
    pattern: /misc/{node_id}/remove
    defaults: { _controller: UCLWebKeyPassBundle:MiscNode:remove }

# Admin zone

ucl_wkp_admin_user_list:
    pattern: /admin/user_list
    defaults: { _controller: UCLWebKeyPassBundle:Admin:showUserList }

ucl_wkp_admin_log_months:
    pattern: /admin/log
    defaults: { _controller: UCLWebKeyPassBundle:Admin:showLogMonths }

ucl_wkp_admin_log:
    pattern: /admin/log/{year_month}
    defaults: { _controller: UCLWebKeyPassBundle:Admin:showLog }

ucl_wkp_admin_remove_user:
    pattern: /admin/{user_id}/remove
    defaults: { _controller: UCLWebKeyPassBundle:Admin:removeUser }

ucl_wkp_admin_edit_user:
    pattern: /admin/{user_id}/edit
    defaults: { _controller: UCLWebKeyPassBundle:Admin:editUser }

ucl_wkp_admin_add_user:
    pattern: /admin/add_user
    defaults: { _controller: UCLWebKeyPassBundle:Admin:addUser }

ucl_wkp_admin_master_key:
    pattern: /admin/master_key
    defaults: { _controller: UCLWebKeyPassBundle:Admin:masterKey }

ucl_wkp_admin_encrypt_master_key:
    pattern: /admin/{user_id}/encrypt_master_key
    defaults: { _controller: UCLWebKeyPassBundle:Admin:encryptMasterKey }

ucl_wkp_admin_show_icons:
    pattern: /admin/icons
    defaults: { _controller: UCLWebKeyPassBundle:Admin:showIcons }

ucl_wkp_admin_add_icon:
    pattern: /admin/add_icon
    defaults: { _controller: UCLWebKeyPassBundle:Admin:addIcon }

ucl_wkp_admin_remove_icon:
    pattern: /admin/remove_icon/{icon}
    defaults: { _controller: UCLWebKeyPassBundle:Admin:removeIcon }

ucl_wkp_admin_show_settings:
    pattern: /admin/settings
    defaults: { _controller: UCLWebKeyPassBundle:Admin:showSettings }

ucl_wkp_admin_set_can_create_account_setting:
    pattern: /admin/set_can_create_account/{new_value}
    defaults: { _controller: UCLWebKeyPassBundle:Admin:setCanCreateAccount }

ucl_wkp_admin_set_session_expiration_timeout_setting:
    pattern: /admin/set_session_expiration_timeout
    defaults: { _controller: UCLWebKeyPassBundle:Admin:setSessionExpirationTimeout }

ucl_wkp_admin_export:
    pattern: /admin/export
    defaults: { _controller: UCLWebKeyPassBundle:Admin:export }

ucl_wkp_admin_do_export:
    pattern: /admin/do_export
    defaults: { _controller: UCLWebKeyPassBundle:Admin:doExport }

ucl_wkp_admin_import:
    pattern: /admin/import
    defaults: { _controller: UCLWebKeyPassBundle:Admin:import }

# Other

ucl_wkp_search:
    pattern: /search
    defaults: { _controller: UCLWebKeyPassBundle:Search:search }

ucl_wkp_edit_user:
    pattern: /edit_user
    defaults: { _controller: UCLWebKeyPassBundle:RootNode:editUser }

ucl_wkp_create_account:
    pattern: /create_account
    defaults: { _controller: UCLWebKeyPassBundle:CreateAccount:createAccount }

ucl_wkp_login:
    pattern: /login
    defaults: { _controller: UCLWebKeyPassBundle:Security:login }

ucl_wkp_login_with_shibboleth:
    pattern: /login_with_shibboleth
    defaults: { _controller: UCLWebKeyPassBundle:Security:loginWithShibboleth }

ucl_wkp_login_check:
    pattern: /login_check

ucl_wkp_login_success:
    pattern: /login_success
    defaults: { _controller: UCLWebKeyPassBundle:Security:loginSuccess }

ucl_wkp_login_private_key:
    pattern: /login_private_key
    defaults: { _controller: UCLWebKeyPassBundle:Security:loginPrivateKey }

ucl_wkp_logout:
    pattern: /logout
    defaults: { _controller: UCLWebKeyPassBundle:Security:logLogout }

ucl_wkp_automatic_logout:
    pattern: /automatic_logout
    defaults: { _controller: UCLWebKeyPassBundle:Security:automaticLogout }

ucl_wkp_logout_real:
    pattern: /logout_real
