# This file is part of WebKeyPass.
#
# Copyright © 2013 Université Catholique de Louvain
#
# WebKeyPass is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# WebKeyPass is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WebKeyPass.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Sébastien Wilmet

# Root

ucl_wkp_root_view:
    pattern: /
    defaults: { _controller: UCLWebKeyPassBundle:RootNode:viewRoot }

ucl_wkp_root_add_category:
    pattern: /add_category
    defaults: { _controller: UCLWebKeyPassBundle:RootNode:addCategory }

# Category

ucl_wkp_category_view:
    pattern: /category/{node_id}
    defaults: { _controller: UCLWebKeyPassBundle:CategoryNode:view }

ucl_wkp_category_edit:
    pattern: /category/{node_id}/edit
    defaults: { _controller: UCLWebKeyPassBundle:CategoryNode:edit }

ucl_wkp_category_add_server:
    pattern: /category/{node_id}/add_server
    defaults: { _controller: UCLWebKeyPassBundle:CategoryNode:addServer }

ucl_wkp_category_add_subcategory:
    pattern: /category/{node_id}/add_subcategory
    defaults: { _controller: UCLWebKeyPassBundle:CategoryNode:addSubCategory }

ucl_wkp_category_add_misc:
    pattern: /category/{node_id}/add_misc
    defaults: { _controller: UCLWebKeyPassBundle:CategoryNode:addMisc }

ucl_wkp_category_remove:
    pattern: /category/{node_id}/remove
    defaults: { _controller: UCLWebKeyPassBundle:CategoryNode:remove }

# Server

ucl_wkp_server_view:
    pattern: /server/{node_id}
    defaults: { _controller: UCLWebKeyPassBundle:ServerNode:view }

ucl_wkp_server_edit:
    pattern: /server/{node_id}/edit
    defaults: { _controller: UCLWebKeyPassBundle:ServerNode:edit }

ucl_wkp_server_add_vm:
    pattern: /server/{node_id}/add_vm
    defaults: { _controller: UCLWebKeyPassBundle:ServerNode:addVM }

ucl_wkp_server_add_misc:
    pattern: /server/{node_id}/add_misc
    defaults: { _controller: UCLWebKeyPassBundle:ServerNode:addMisc }

ucl_wkp_server_move:
    pattern: /server/{node_id}/move
    defaults: { _controller: UCLWebKeyPassBundle:ServerNode:move }

ucl_wkp_server_remove:
    pattern: /server/{node_id}/remove
    defaults: { _controller: UCLWebKeyPassBundle:ServerNode:remove }

# Virtual Machine

ucl_wkp_vm_view:
    pattern: /vm/{node_id}
    defaults: { _controller: UCLWebKeyPassBundle:VMNode:view }

ucl_wkp_vm_edit:
    pattern: /vm/{node_id}/edit
    defaults: { _controller: UCLWebKeyPassBundle:VMNode:edit }

ucl_wkp_vm_add_misc:
    pattern: /vm/{node_id}/add_misc
    defaults: { _controller: UCLWebKeyPassBundle:VMNode:addMisc }

ucl_wkp_vm_move:
    pattern: /vm/{node_id}/move
    defaults: { _controller: UCLWebKeyPassBundle:VMNode:move }

ucl_wkp_vm_remove:
    pattern: /vm/{node_id}/remove
    defaults: { _controller: UCLWebKeyPassBundle:VMNode:remove }

# Misc

ucl_wkp_misc_view:
    pattern: /misc/{node_id}
    defaults: { _controller: UCLWebKeyPassBundle:MiscNode:view }

ucl_wkp_misc_edit:
    pattern: /misc/{node_id}/edit
    defaults: { _controller: UCLWebKeyPassBundle:MiscNode:edit }

ucl_wkp_misc_add_misc:
    pattern: /misc/{node_id}/add_misc
    defaults: { _controller: UCLWebKeyPassBundle:MiscNode:addMisc }

ucl_wkp_misc_move:
    pattern: /misc/{node_id}/move
    defaults: { _controller: UCLWebKeyPassBundle:MiscNode:move }

ucl_wkp_misc_remove:
    pattern: /misc/{node_id}/remove
    defaults: { _controller: UCLWebKeyPassBundle:MiscNode:remove }
