ucl_wkp_main_view:
    pattern: /
    defaults: { _controller: UCLWebKeyPassBundle:Main:view }

ucl_wkp_node_view:
    pattern: /{node}
    defaults: { _controller: UCLWebKeyPassBundle:Node:view }

ucl_wkp_node_edit:
    pattern: /{node}/edit
    defaults: { _controller: UCLWebKeyPassBundle:Node:view }

ucl_wkp_node_add:
    pattern: /{node}/add
    defaults: { _controller: UCLWebKeyPassBundle:Node:view }

ucl_wkp_node_move:
    pattern: /{node}/move
    defaults: { _controller: UCLWebKeyPassBundle:Node:view }

ucl_wkp_node_remove:
    pattern: /{node}/remove
    defaults: { _controller: UCLWebKeyPassBundle:Node:view }
