security:
    encoders:
        UCL\WebKeyPassBundle\Entity\User:
            algorithm:        sha256
            encode_as_base64: false
            iterations:       2

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        administrators:
            entity: { class: UCLWebKeyPassBundle:User, property: username }

    firewalls:
        create_account:
            pattern: ^/WebKeyPass/create_account
            security: false

        login:
            pattern: ^/WebKeyPass/login$
            security: false

        secured_area:
            pattern: ^/WebKeyPass/
            form_login:
                check_path: /WebKeyPass/login_check
                login_path: /WebKeyPass/login
                always_use_default_target_path: true
                default_target_path: /WebKeyPass/login_success
            logout:
                path:   /WebKeyPass/logout_real
                target: /WebKeyPass/

    access_control:
        - { path: ^/WebKeyPass/admin, roles: ROLE_ADMIN }
